// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// Ping defines model for Ping.
type Ping struct {
	Status *string `json:"status,omitempty"`
}

// CreateLogoResponses defines model for CreateLogoResponses.
type CreateLogoResponses struct {
	Url *string `json:"url,omitempty"`
}

// SquareResponses defines model for SquareResponses.
type SquareResponses struct {
	SquareX *int `json:"square_x,omitempty"`
}

// CreateLogoRequest defines model for CreateLogoRequest.
type CreateLogoRequest struct {
	// Имя файла логотипа
	Filename *string `json:"filename,omitempty"`

	// Изображение в (base64)
	Logo *[]byte `json:"logo,omitempty"`
}

// SquareRequest defines model for SquareRequest.
type SquareRequest struct {
	X *int `json:"x,omitempty"`
}

// PostLogoJSONRequestBody defines body for PostLogo for application/json ContentType.
type PostLogoJSONRequestBody CreateLogoRequest

// PostSquareJSONRequestBody defines body for PostSquare for application/json ContentType.
type PostSquareJSONRequestBody SquareRequest
